import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        background: "#f7f9fb",
        "tertiary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        primary: "#3525cd",
        surface: "#f7f9fb",
        outline: "#777587",
        "on-surface": "#191c1e",
        "primary-fixed": "#e2dfff",
        "secondary-fixed": "#dae2fd",
        "on-error-container": "#93000a",
        secondary: "#565e74",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#0f0069",
        "primary-container": "#4f46e5",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#ccdcf7",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-container": "#516177",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-on-surface": "#eff1f3",
        tertiary: "#3a495f",
        "surface-container": "#eceef0",
        "on-secondary-container": "#5c647a",
        "on-background": "#191c1e",
        "on-surface-variant": "#464555",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#131b2e",
        "inverse-primary": "#c3c0ff",
        card: "#E2E8F0",
        active: { bg: "#e8f5e9", text: "#2e7d32", border: "#c8e6c9" },
        disabled: { bg: "#fef3e2", text: "#b45309", border: "#fde68a" },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        base: "8px",
        gutter: "24px",
        sm: "12px",
        xs: "4px",
        md: "24px",
        xl: "64px",
        "margin-desktop": "48px",
        lg: "40px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 12px rgba(15, 23, 42, 0.03)",
        "card-hover": "0 12px 24px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [forms],
};
