import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "var(--qf-error)",
        "error-container": "var(--qf-error-container)",
        background: "var(--qf-background)",
        "tertiary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        primary: "var(--qf-primary)",
        surface: "var(--qf-surface)",
        outline: "var(--qf-outline)",
        "on-surface": "var(--qf-on-surface)",
        "primary-fixed": "var(--qf-primary-fixed)",
        "secondary-fixed": "#dae2fd",
        "on-error-container": "var(--qf-on-error-container)",
        secondary: "var(--qf-secondary)",
        "inverse-surface": "var(--qf-inverse-surface)",
        "on-primary-fixed": "#0f0069",
        "primary-container": "var(--qf-primary-container)",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "surface-container-low": "var(--qf-surface-container-low)",
        "surface-container-lowest": "var(--qf-surface-container-lowest)",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "var(--qf-surface-container-highest)",
        "on-tertiary": "#ffffff",
        "on-primary": "var(--qf-on-primary)",
        "surface-variant": "var(--qf-surface-container-highest)",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-high": "var(--qf-surface-container-high)",
        "on-tertiary-container": "#ccdcf7",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-container": "#516177",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-on-surface": "var(--qf-inverse-on-surface)",
        tertiary: "#3a495f",
        "surface-container": "var(--qf-surface-container)",
        "on-secondary-container": "#5c647a",
        "on-background": "var(--qf-on-background)",
        "on-surface-variant": "var(--qf-on-surface-variant)",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-primary-container": "var(--qf-on-primary-container)",
        "surface-dim": "var(--qf-surface-dim)",
        "surface-bright": "var(--qf-background)",
        "outline-variant": "var(--qf-outline-variant)",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#131b2e",
        "inverse-primary": "#c3c0ff",
        card: "var(--qf-card)",
        active: {
          bg: "var(--qf-active-bg)",
          text: "var(--qf-active-text)",
          border: "var(--qf-active-border)",
        },
        disabled: {
          bg: "var(--qf-disabled-bg)",
          text: "var(--qf-disabled-text)",
          border: "var(--qf-disabled-border)",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        base: "10px",
        gutter: "30px",
        sm: "15px",
        xs: "5px",
        md: "30px",
        xl: "80px",
        "margin-desktop": "60px",
        lg: "50px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["60px", { lineHeight: "70px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["18px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["35px", { lineHeight: "45px", fontWeight: "600" }],
        "body-sm": ["18px", { lineHeight: "25px", fontWeight: "400" }],
        "label-sm": ["15px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "50px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["20px", { lineHeight: "30px", fontWeight: "400" }],
        "body-lg": ["23px", { lineHeight: "35px", fontWeight: "400" }],
        "headline-sm": ["25px", { lineHeight: "35px", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 12px rgba(15, 23, 42, 0.03)",
        "card-hover": "0 12px 24px rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [forms],
};
